#!/bin/bash

# Path to the custom sysctl configuration file for fwg
SYSCTL_PATH="/etc/sysctl.d/90-fast-wireguard.conf"

# Enable IPv4 packet forwarding in the kernel
network::enable_forwarding() {
    echo "Checking IPv4 forwarding status..."

    # Read the current kernel parameter value
    if [[ $(sysctl -n net.ipv4.ip_forward) -eq 1 ]]; then
        echo "IPv4 forwarding is already enabled."
    else
        echo "Enabling IPv4 forwarding..."

        # Create a dedicated config file to ensure persistence after reboot
        # tee is used to write to a system-protected path
        sudo tee "${SYSCTL_PATH}" > /dev/null <<EOF
# This file is auto generated by Fast WireGuard.
# To remove, use fwg uninstall
net.ipv4.ip_forward=1
EOF

        # Apply the specific configuration file immediately
        if sudo sysctl -p "${SYSCTL_PATH}" > /dev/null; then
            echo "Successfully enabled IPv4 forwarding."
        else
            echo "Error: Failed to apply sysctl settings."
            return 1
        fi
    fi
}

# Restore IPv4 forwarding settings to system defaults
network::restore_forwarding() {
    echo "Restoring IPv4 forwarding settings..."

    if [[ -f "${SYSCTL_PATH}" ]]; then
        echo "Removing custom configuration: ${SYSCTL_PATH}"
        sudo rm -f "${SYSCTL_PATH}"

        # Trigger a system-wide sysctl reload to fall back to default configs
        # This prevents breaking other services that might also need forwarding
        echo "Reloading system-wide sysctl configuration..."
        sudo sysctl --system > /dev/null

        echo "IPv4 forwarding settings restored to system defaults."
    else
        echo "No custom fwg configuration found. Nothing to restore."
    fi
}
