package system

import (
	"fast-wireguard/pkg/utils"
	"fmt"
	"os"
	"strings"
)

var (
	// sysctlConfigPath is the path to the sysctl configuration file for IP forwarding
	sysctlConfigPath = "/etc/sysctl.d/99-fast-wireguard.conf"
	configContent    = `#This file is auto-generated by fast-wireguard.
#Please do not edit manually.
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
`
)

func isForwardingEnabled(version string) bool {
	switch version {
	case "ipv4":
		return checkSysctl("/proc/sys/net/ipv4/ip_forward")
	case "ipv6":
		return checkSysctl("/proc/sys/net/ipv6/conf/all/forwarding")
	default:
		return false
	}
}

func checkSysctl(s string) bool {
	content, err := os.ReadFile(s)
	if err != nil {
		return false
	}
	return strings.TrimSpace(string(content)) == "1"
}

/*
Write Configuration to enable IP forwarding on Linux systems.
Returns an error if the operation fails.
*/
func EnableIPForwarding() error {
	// Write ip_forwarding configuration
	if _, err := os.Stat(sysctlConfigPath); err == nil {
		// If the file exists, do nothing
		fmt.Println("Configuration file for IP forwarding already exists.")
		// // Ask the user to confirm overwriting
		// if utils.PromptConfirm("Do you want to overwrite this file?", false) {
		// 	fmt.Println("Overwriting configuration file for IP forwarding...")
		// 	if err := os.WriteFile(sysctlConfigPath, []byte(configContent), 0644); err != nil {
		// 		return err
		// 	}
		// }
	} else if os.IsNotExist(err) {
		// If the config file does not exist, create it
		if err := os.WriteFile(sysctlConfigPath, []byte(configContent), 0644); err != nil {
			return err
		}
		fmt.Println("✅ Configuration file for IP forwarding created.")
	} else {
		return fmt.Errorf("Failed to check sysctl config file: %w", err)
	}

	// Detect the ip4 forwarding and ipv6 forwarding
	if isForwardingEnabled("ipv4") && isForwardingEnabled("ipv6") {
		fmt.Println("IP forwarding is already enabled.")
		return nil
	}

	// Apply the sysctl settings
	if err := utils.RunAsRoot("sysctl -p", sysctlConfigPath); err != nil {
		return fmt.Errorf("Failed to apply sysctl settings: %w", err)
	}
	fmt.Println("✅ IP forwarding enabled successfully.")
	return nil
}

/*
RestoreIPForwarding restores IP forwarding by removing the sysctl configuration.
Returns an error if the operation fails.
*/
func RestoreIPForwarding() error {
	// Remove the sysctl configuration file
	if err := os.Remove(sysctlConfigPath); err != nil {
		// If file doesn't exist, we can continue
		if !os.IsNotExist(err) {
			return fmt.Errorf("Failed to remove sysctl config file: %w", err)
		} else {
			return nil
		}
	}

	// 1. Reset to default (0) first
	// We disable it first, so that if no other config file requests it, it stays disabled.
	utils.RunAsRootSilent("sysctl -w net.ipv4.ip_forward=0")
	utils.RunAsRootSilent("sysctl -w net.ipv6.conf.all.forwarding=0")

	// 2. Reload all system configurations
	// If other services (like Docker) have their own config files enabling forwarding,
	// this command will re-enable it, preserving their functionality.
	if err := utils.RunAsRootSilent("sysctl --system"); err != nil {
		return fmt.Errorf("Failed to reload sysctl settings: %w", err)
	}

	fmt.Println("✅ IP forwarding configuration removed successfully.")
	return nil
}
