# Auto-generated by fast-wireguard
[Interface]
Address = {{ .Address }}
ListenPort = {{ .ListenPort }}
PrivateKey = {{ .PriKey }}
MTU = {{ .MTU }}

# --- Core Network Forwarding Rules (iptables) ---
PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o {{ .PhysicalInterface }} -j MASQUERADE
PostUp = ip6tables -A FORWARD -i %i -j ACCEPT
PostUp = ip6tables -t nat -A POSTROUTING -o {{ .PhysicalInterface }} -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o {{ .PhysicalInterface }} -j MASQUERADE
PostDown = ip6tables -D FORWARD -i %i -j ACCEPT
PostDown = ip6tables -t nat -D POSTROUTING -o {{ .PhysicalInterface }} -j MASQUERADE

# ------------------------------------------------------
# Client list
# ------------------------------------------------------
